[tool.poetry]
name = "bniehuser-flask"
version = "0.1.0"
description = ""
authors = ["Barry Niehuser <bniehuser@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.17.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
