[tool.poetry]
name = "bniehuser-flask"
version = "0.1.0"
description = ""
authors = ["Barry Niehuser <bniehuser@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.65.1"
uvicorn = "^0.14.0"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.17.1"
pytest = "^6.2.4"
pytest-flask = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
